name: mga2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::r-base=4.0.3
  - conda-forge::r-tidyverse=1.3.0
  - conda-forge::r-optparse=1.6.6
  - conda-forge::r-svglite=2.0.0
  - conda-forge::fonts-conda-forge=1
  - bioconda::bowtie=1.3.0
  - bioconda::exonerate=2.4.0
