name: mga2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::rust=1.76.0
  - conda-forge::r-base=4.3.2
  - conda-forge::r-tidyverse=2.0.0
  - conda-forge::r-optparse=1.7.4
  - conda-forge::r-svglite=2.1.3
  - conda-forge::fonts-conda-forge=1
  - bioconda::bowtie=1.3.1
  - bioconda::exonerate=2.4.0
